#!/bin/bash

kernel="$(uname -r)"
memory="$(free -h | awk '/^Speicher:/ {print $3 "/" $2}')"
updates=$(checkupdates | wc -l)
uptime="$(uptime --pretty | sed -e 's/up //g' -e 's/ days/d/g' -e 's/ day/d/g' -e 's/ hours/h/g' -e 's/ hour/h/g' -e 's/ minutes/m/g' -e 's/, / /g')"

echo -e "Kernel:  $kernel"
echo -e "RAM:     $memory"
echo -e "Updates: $updates"
echo -e "Uptime:  $uptime"
